[mgr]
prepend_keymap = [
	{ on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
	{ on = "<Tab>", run = "tab_switch 1 --relative", desc = "Switch to next tab" },
	{ on = "<S-Tab>", run = "tab_switch -1 --relative", desc = "Switch to previous tab" },
	{ on = "i", run = "spot", desc = "Spot file info" },
	{ on = ["g", "?"], run = "help", desc = "Open help" },
	# Map toggle to <Space><Space> (frees up <Space> as leader)
	{ on = [" ", " "], run = "toggle", desc = "Toggle selection" },
	{ on = [" ", "y", "y"], run = "copy path", desc = "Copy full path" },
	{ on = [" ", "y", "a"], run = "copy path", desc = "Copy full path" },
	{ on = [" ", "y", "f"], run = "copy filename", desc = "Copy filename" },
	{ on = [" ", "y", "d"], run = "copy dirname", desc = "Copy directory path" },
	{ on = [" ", "f", "f"], run = "plugin fzf", desc = "Search files " },
	{ on = [" ", "f", "d"], for = "unix", run = 'shell "dir=$(fd -t d | fzf) && ya emit cd -- \"$dir\"" --block', desc = "Search directories " },
	{ on = [" ", "f", "z"], run = "plugin zoxide", desc = "Search zoxide" },
	{ on = [" ", "x"], run = "tab_close", desc = "Close tab" },
	{ on = [" ", "p", "u"], run = "plugin toggle-pane min-parent", desc = "Toggle parent pane" },
	{ on = [" ", "p", "U"], run = "plugin toggle-pane max-parent", desc = "Maximize parent pane" },
	{ on = [" ", "p", "c"], run = "plugin toggle-pane min-current", desc = "Toggle current pane" },
	{ on = [" ", "p", "C"], run = "plugin toggle-pane max-current", desc = "Maximize current pane" },
	{ on = [" ", "p", "p"], run = "plugin toggle-pane min-preview", desc = "Toggle preview" },
	{ on = [" ", "p", "P"], run = "plugin toggle-pane max-preview", desc = "Maximize preview" },
	{ on = [" ", "p", "r"], run = "plugin toggle-pane reset", desc = "Reset pane layout" },
	{ on = [" ", ":"], for = "unix", run = 'shell "$SHELL" --block', desc = "Open $SHELL here" },
]

[tasks]
prepend_keymap = [
	{ on = "q", run = "close", desc = "Close task manager" },
]

[select]
prepend_keymap = [
	{ on = "q", run = "close", desc = "Close select" },
]

[input]
prepend_keymap = [
	{ on = "q", run = "close", desc = "Close input" },
]

[help]
prepend_keymap = [
	{ on = "q", run = "escape", desc = "Close help" },
]

[cmp]
prepend_keymap = [
	{ on = "q", run = "close", desc = "Close completion" },
]

[spot]
prepend_keymap = [
	{ on = "q", run = "close", desc = "Close spot" },
]
