alias -g H="| head"
alias -g L="| less"
alias -g VL="| vless"
alias -g G="| grep -i"
alias -g F="| fzf --reverse"

# Copy to system clipboard
: ${IS_MACOS:=$([[ $OSTYPE == darwin* ]] && echo true || echo false)}

if [[ $IS_MACOS == true ]]; then
    alias -g C="| pbcopy"
elif type xclip >/dev/null 2>&1 ; then
    alias -g C="| xclip -selection clipboard"
fi
# Copy to tmux clipboard
alias -g CT="| tmux load-buffer -"

# redirect stderr to stdout
alias -g RE="2>&1"
# No stdout
alias -g NO=">/dev/null"
# No stderr
alias -g NE="2>/dev/null"
# No stdout and stderr
alias -g NOE=">/dev/null 2>&1"

alias tailf="tail -f"
alias v="vim"
alias vi="vim"
alias tat="tmux new -A -s default"

alias proxy_on="export {http,https,ftp}_proxy=http://127.0.0.1:7890; export socks_proxy=socks5://127.0.0.1:7891; no_proxy='localhost,127.0.0.1,*.local'"
alias proxy_off="unset {http,https,ftp,all,socks,no}_proxy"

# lsd
if type lsd >/dev/null 2>&1 ; then
    alias ls="lsd"
    alias ll="lsd -l"
    alias la="lsd -la"
    alias lt="lsd --tree"
fi

# git
alias g="git"
# Generated by bin/generate-git-aliases.
source "$DOTFILES/zsh/git-aliases.zsh"

# uv
if type uv >/dev/null 2>&1; then
    alias uva="uv add"
    alias uvp="uv pip"
    alias uvpy="uv python"
    alias uvr="uv run"
    alias uvs="uv sync"
    alias uvv="uv venv"
fi
